export const SET_NEW_TASK_DESCRIPTION = 'taskList.SET_NEW_TASK_DESCRIPTION';

export const GET_TASKS_STARTED = 'taskList.GET_TASKS_STARTED';
export const GET_TASKS_SUCCESS = 'taskList.GET_TASKS_SUCCESS';
export const GET_TASKS_FAILURE = 'taskList.GET_TASKS_FAILURE';

export const ADD_TASK_STARTED = 'taskList.ADD_TASK_STARTED';
export const ADD_TASK_SUCCESS = 'taskList.ADD_TASK_SUCCESS';
export const ADD_TASK_FAILURE = 'taskList.ADD_TASK_FAILURE';

export const DELETE_TASK_STARTED = 'taskList.DELETE_TASK_STARTED';
export const DELETE_TASK_SUCCESS = 'taskList.DELETE_TASK_SUCCESS';
export const DELETE_TASK_FAILURE = 'taskList.DELETE_TASK_FAILURE';