name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

jobs:
  dotnet-test:
    name: Backend Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [
          { tfm: net8.0, version: '8.0.x' },
        ]
    env:
      BUILD_CONFIG: Release
      SOLUTION: ReactReduxTodo.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet.version }}

    - name: Restore
      run: dotnet restore $SOLUTION

    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore

    - name: Test
      run: dotnet test $SOLUTION --configuration $BUILD_CONFIG --no-build --verbosity normal

  frontend-test:
    name: Frontend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ClientApp

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './ClientApp/package-lock.json'

    - name: Install dependencies
      run: npm ci

    - name: Run frontend tests
      run: npm test
